<?php
/** @var \Swarming\SubscribePro\Block\ApplePay\Button $block */
?>
<script>
    var window.spApplePayConfig = {
        createSessionUrl: '<?php echo $block->getCreateSessionUrl(); ?>',
        merchantDomainName: '<?php echo $block->getMerchantDomainName(); ?>',
        merchantDisplayName: '<?php echo $block->getMerchantDisplayName(); ?>',
        onShippingContactSelectedUrl: '<?php echo $block->getOnShippingContactSelectedUrl(); ?>',
        onShippingMethodSelectedUrl: '<?php echo $block->getOnShippingMethodSelectedUrl(); ?>',
        onPaymentAuthorizedUrl: '<?php echo $block->getOnPaymentAuthorizedUrl(); ?>',
        accessToken: '<?php echo $block->getCustomerAccessToken(); ?>'
    };
</script>
